### ISSUE TITLE
cPanel randomly reverts icons to original version

### ISSUE THREAD

**Issue by ghost** [zerosignalproductions/cPanel-2012-Theme#2]
I plan to replace the icon code with the generated CSS so that cPanel has no control over the image file.

**Comment by zerosignalproductions** [comment]
After doing some more research it seems this is a bug that has supposedly been fixed already. I'm not sure why my server is still affected but if anyone else notices this issue I'll manually include the icon CSS instead of having cPanel generate it.

Link to thread noting this problem: http://forums.cpanel.net/f8/cpanel-keeps-reverting-branding-changes-case-59099-a-276561.html#post1168082

**Comment by qrohlf** [comment]
Still seems to be happening on my server.

**Comment by zerosignalproductions** [comment]
Hey, I haven't been able to update this at all in quite a while. I never figured out why cPanel was reverting icons and I couldn't find anything on how to actually fix it.

Sorry bout that, but if you happen to find a fix, I'll be glad to update this repository or merge any changes. Thanks!

**Comment by qrohlf** [comment]
I've actually switched from Apache to nginx and dumped cPanel, so I'm afraid I won't be of too much help. Thanks for making my cPanel days more bearable with your theme, though!

**Comment by zerosignalproductions** [comment]
I'm going to go ahead and close this as I can't find a solution anywhere. I've gone ahead and replaced the header icons so the theme will still look good even if the main icons get replaced.
